apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
<<<<<<< HEAD
    - image: centos:7.0
=======
    - image: oped-jdk-17
>>>>>>> parent of b327d3d (added nodejs in pod.yaml)
    name: vikas
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
    - mountPath: /tmp/hostpath
      name: dir_volume
  volumes:
  - name: testvolume
    hostPath:
      path: /tmp/data 


