apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
    - image: centos:7.0
    name: vikas
    command: ["/bin/bash", "-c", "sleep 10000"]
    volumeMounts:
    - mountPath: /tmp/hostpath
      name: dir_volume
  volumes:
  - name: testvolume
    hostPath:
      path: /tmp/data 


